export enum TypesEnum {
  NEUTRAL = "neutral",
  GRASS = "grass",
  FIRE = "fire",
  WATER = "water",
  ELECTRIC = "electric",
  ICE = "ice",
  GROUND = "ground",
  DARK = "dark",
  DRAGON = "dragon",
}


export enum ItemTypesEnum {
  WEAPON = "weapon",
  PALSPHERE = "palSphere",
  ARMOR = "armor",
  ACCESSORY = "accessory",
  MATERIAL = "material",
  CONSUMABLE = "consumable",
  AMMO = "ammo",
  FOOD = "food",
  ESSENTIAL = "essential",
  GLIDER = "glider",
  BLUEPRINT = "blueprint"
}

export enum ItemRecipeTypeEnum {
  "WOOL" = "Wool",
  "FLOUR" = "Flour",
  "TOMATO" = "Tomato",
  "WOOD" = "Wood",
  "VENOM GLAND" = "Venom Gland",
  "NAIL" = "Nail",
  "MAMMOREST MEAT" = "Mammorest Meat",
  "FIBER" = "Fiber",
  "ICE ORGAN" = "Ice Organ",
  "FLAME ORGAN" = "Flame Organ",
  "WHEAT" = "Wheat",
  "TOCOTOCO FEATHER" = "Tocotoco Feather",
  "PENKING PLUME" = "Penking Plume",
  "PURE QUARTZ" = "Pure Quartz",
  "HIGH QUALITY PAL OIL" = "High Quality Pal Oil",
  "ELECTRIC ORGAN" = "Electric Organ",
  "RAW DUMUD" = "Raw Dumud",
  "CAPRITY MEAT" = "Caprity Meat",
  "SULFUR" = "Sulfur",
  "REFINED INGOT" = "Refined Ingot",
  "BEAUTIFUL FLOWER" = "Beautiful Flower",
  "KATRESS HAIR" = "Katress Hair",
  "RAW KELPSEA" = "Raw Kelpsea",
  "PALDIUM FRAGMENT" = "Paldium Fragment",
  "CEMENT" = "Cement",
  "ORE" = "Ore",
  "REINDRIX VENISON" = "Reindrix Venison",
  "LEATHER" = "Leather",
  "STONE" = "Stone",
  "LETTUCE" = "Lettuce",
  "CLOTH" = "Cloth",
  "CARBON FIBER" = "Carbon Fiber",
  "PAL FLUIDS" = "Pal Fluids",
  "EGG" = "Egg",
  "LAMBALL MUTTON" = "Lamball Mutton",
  "GALECLAW POULTRY" = "Galeclaw Poultry",
  "RED BERRIES" = "Red Berries",
  "HIGH QUALITY CLOTH" = "High Quality Cloth",
  "ANCIENT CIVILIZATION PARTS" = "Ancient Civilization Parts",
  "MILK" = "Milk",
  "GUNPOWDER" = "Gunpowder",
  "PAL METAL INGOT" = "Pal Metal Ingot",
  "MOZZARINA MEAT" = "Mozzarina Meat",
  "MUSHROOM" = "Mushroom",
  "CHARCOAL" = "Charcoal",
  "COAL" = "Coal",
  "CIRCUIT BOARD" = "Circuit Board",
  "BRONCHERRY MEAT" = "Broncherry Meat",
  "RUSHOAR PORK" = "Rushoar Pork",
  "HONEY" = "Honey",
  "EIKTHYRDEER VENISON" = "Eikthyrdeer Venison",
  "BONE" = "Bone",
  "GUMOSS LEAF" = "Gumoss Leaf",
  "CHIKIPI POULTRY" = "Chikipi Poultry",
  "HORN" = "Horn",
  "INGOT" = "Ingot",
  "POLYMER" = "Polymer"
}
